### PR TITLE
v 2.0

### PR DESCRIPTION
**Pull request by ComandPromt**
I have improved the program by adding a graphical environment to it. Now it is much easier for the user to open videos, put the section that he wants to convert to gif and convert the video to gif.

It also has more options, they are in the configuration menu. The user will be able to use watermarks and text for the gifs, being able to choose the text, color and positioning of the same within the gif

### CODE REVIEW

**Comment by kgmyatthu** [comment]
Hi does your version of vdo2gif utilize my code in vdo2gif.py?

**Comment by ComandPromt** [comment]
> 
> 
> Hi does your version of vdo2gif utilize my code in vdo2gif.py?

Hi there. The program uses your script.

First you go from video to video with ffmpeg (in the output video it comes out with the program's configuration options)

With that video, your program is used to convert it to gif with the program's options.

Here is a video where you can see how it works. 

https://www.tiktok.com/@hoopsearring4ever/video/6999397507683847430?lang=es&is_copy_url=0&is_from_webapp=v1&sender_device=pc&sender_web_id=6991107558728041989

**Comment by kgmyatthu** [comment]
Hi Thank you for replying i'm happy you improve the code, but there's one last question, does your version work offline?

**Comment by ComandPromt** [comment]
> Hi Thank you for replying i'm happy you improve the code, but there's one last question, does your version work offline?

The program uses an API made by me. https://apiperiquito.herokuapp.com/

This API returns a file name of the format year_month_day_hour_minutes_seconds

This is to avoid overwriting the output of the gif in case of saving multiple gifs on the same video.

If you accept the pull request, I will send you a second pull with the improved code. The problem of the relative paths and operation in Windows and Linux is fixed, as well as some bugs that I ignored, I have been testing it and it no longer gives errors. Greetings, my name is Ramon, nice to meet you

**Comment by kgmyatthu** [comment]
Hi Ramon, I think your project is really cool, but it has deviated so much from my original intended purpose which is not being needed a GUI and completely work offline. While the first purpose for not needing a GUI is fulfilled, the second purpose is not. I request you made the whole project completely work offline and made a second pull request. I'm closing this PR for now. 
You're also feel free to make the whole project your own if you wish. Im okay with that. But if you still wanna make a pull request, i suggest you made the code work offline.

**Pull request closed without merging**
